apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 889951087651.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 889951087651.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 368781fb
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
